### ISSUE TITLE
Environment variable name not consistent

### ISSUE THREAD

**Issue by chengchingwen** [oxinabox/DataDeps.jl#101]
I accidentally found that the call to get printing period miss a 's' in the variable name. Should be `"DATADEPS_ALWAYS_ACCEPT"`
https://github.com/oxinabox/DataDeps.jl/blob/626cedb5eb683dee8bcbe1868d0ce236c4fb4afc/src/fetch_helpers.jl#L12-L13

**Comment by chengchingwen** [comment]
So I found that on the documentation, only `DATADEP_PROGRESS_UPDATE_PERIOD` doesn't start with `DATADEPS` but `DATADEP`.

**Comment by oxinabox** [comment]
Yeah, both should have an `S`,
Want to make the PR?

**Comment by chengchingwen** [comment]
sure
