### ISSUE TITLE
Infinite loop of user prompts when running headless tests

### ISSUE THREAD

**Issue by KristofferC** [oxinabox/DataDeps.jl#104]
I am running tests on julia packages to check for regressions. I just filled up a system with a couple of 250GB package test-logs all depending on DataDeps.jl and all containing content of the type:

![Screenshot-20191008154214-1168x388](https://user-images.githubusercontent.com/1282691/66401256-2a6ac880-e9e3-11e9-98d1-a025c1b32ef3.png)

I guess it keeps spinning in 

https://github.com/oxinabox/DataDeps.jl/blob/7e3696e762bfb068b61288d54a526c703c2e0ae2/src/util.jl#L79-L88

Kind of a dup of https://github.com/oxinabox/DataDeps.jl/issues/84 but it doesn't seem fixed.

**Comment by oxinabox** [comment]
We can't use `isinteractive` to check if user input is available as that does not work when triggering tests. Since tests to not run in interactive.
Which is a common use case.


I don't understand what this has stopped working
https://github.com/oxinabox/DataDeps.jl/blob/c82892ab0b72c1d544aa73b106cabbc73d90ea33/src/util.jl#L54-L61

**Comment by KristofferC** [comment]
> that does not work when triggering tests.

Having tests that require manual input seems unworkable and it seems that these test should be rewritten somehow.

Anyway, as a path of leat resistance, perhaps just change the `while true` to something like `for _ in 1:20` or something to avoid pathological cases like this.

**Comment by oxinabox** [comment]
I really want to get to the bottom of this one day.
I worry that maybe this means that something has changed in how julia handles closed streams.
(e.g. https://github.com/JuliaLang/julia/issues/1306 has regressed before).

>  Having tests that require manual input seems unworkable and it seems that these tests should be rewritten somehow.

Sometimes, sometime not.
In CI you set the `ENV["DATADEP_ALWAY_ACCEPT"]` flag.


As path of least resistance,
I suggest that PkgEval should set: `ENV["CI"] = true`
DataDeps will not prompt for user input if `ENV["CI"]="true"`
and I feel like it is a valid call to say that PkgEval is a kind of CI.
All CI platforms set that enviroment variable.


https://github.com/oxinabox/DataDeps.jl/blob/c82892ab0b72c1d544aa73b106cabbc73d90ea33/src/resolution_automatic.jl#L21-L34

**Comment by oxinabox** [comment]
Closed by #105

**Comment by hungpham3112** [comment]
Hi, today when I'm working with MNIST on Pluto.jl, I have a problem.
```
Either user provided invalid input 100 times; or something hasgone wrong with the IO reading. Please comment on:

https://github.com/oxinabox/DataDeps.jl/issues/104
```

![image](https://github.com/oxinabox/DataDeps.jl/assets/75968004/ca6cd905-fd40-446c-8213-200d476615b4)
![image](https://github.com/oxinabox/DataDeps.jl/assets/75968004/c686111d-1278-4943-85af-74eef6896dab)

I reported [issue](https://github.com/fonsp/Pluto.jl/issues/2582) in Pluto.jl and waiting response

**Comment by oxinabox** [comment]
See my response in the Pluto issue: https://github.com/fonsp/Pluto.jl/issues/2582#issuecomment-1586528882
