### ISSUE TITLE
Can't unpack a .xz

### ISSUE THREAD

**Issue by aviks** [oxinabox/DataDeps.jl#106]
Datadeps can upack a `.tar.xz` or a `.txz` but not a bare `.xz`. That is 😞

**Comment by oxinabox** [comment]
What is a .xz? :joy:  (only 1/2 joking).
Do you have an example file?
What OS?

**Comment by Ayushk4** [comment]
Here is an example file from TextAnalysis.jl v0.6.0 release files. 

https://github.com/JuliaText/TextAnalysis.jl/releases/download/v0.6.0/pretrained_lm_weights.bson.xz

Release link - https://github.com/JuliaText/TextAnalysis.jl/releases/tag/v0.6.0

**Comment by aviks** [comment]
Even better, I can show you the code : 
https://github.com/oxinabox/DataDeps.jl/blob/1e82e5cefa884f2e56a707f503eb0204169e68ce/src/post_fetch_helpers.jl#L9-L10

`.xz` files are unpacked only in conjunction with a `.tar`

**Comment by oxinabox** [comment]
PR? I am at a conference so won't have time to look at this myself for a while
