### ISSUE TITLE
Display progress of large downloads

### ISSUE THREAD

**Issue by cossio** [oxinabox/DataDeps.jl#109]
It would be nice if `DataDeps` displayed progress for long downloads.

**Comment by oxinabox** [comment]
It does log the progress. It uses `HTTP.download` which logs progress and speed and a few other things.
Turning that info into a progress bar is a problem for the logger 

OhMyLog used to do it, but I have discontinued that.
@c42f and @tkf have been working on some thing in the area.

It it's not working right this needs to be resolved in HTTP.jl
so feel free to reopen this issue there if problems persist.
With a MWE if you could
