### ISSUE TITLE
Docstring mismatch for `Base.download` method

### ISSUE THREAD

**Issue by Evizero** [oxinabox/DataDeps.jl#11]
The signature in the docstring makes it seem like there are keyword argument, where the actual method just has positional ones. (https://github.com/oxinabox/DataDeps.jl/blob/master/src/resolution_automatic.jl#L10-L14)

I am working on the MLDatasets integration and want to provide a `MNIST.download(...)` method etc. currently I have to do it like this if I want to support custom directories, which seems a bit verbose:

```julia
    function download(dir; i_accept_the_terms_of_use = nothing)
        datadep = DataDeps.registry["MNIST"]
        if i_accept_the_terms_of_use == nothing
            DataDeps.download(datadep, dir)
        else
            DataDeps.download(
                datadep,
                dir,
                datadep.remotepath,
                i_accept_the_terms_of_use
            )
        end
    end
```

It would be nice if there was a simple interface for saying "either I provide a custom value (i.e. accept terms, localdir) or behave according to DataDeps default". This would be nice because I would like it so that if a user doesn't say "i_accept_the_terms_of_use" it shouldn't just move on, but instead use the default behaviour of `env_bool("DATADEPS_ALWAY_ACCEPT")`.

**Comment by oxinabox** [comment]
yes, I think you are correct on all points here.

**Comment by Evizero** [comment]
For the sake of completeness, this is how I currently do it in the PR

```julia
function with_accept(f, manual_overwrite)
    auto_accept = if manual_overwrite == nothing
        get(ENV, "DATADEPS_ALWAY_ACCEPT", false)
    else
        manual_overwrite
    end
    withenv(f, "DATADEPS_ALWAY_ACCEPT" => string(auto_accept))
end

function download_dep(depname,
                      dir = DataDeps.determine_save_path(depname);
                      i_accept_the_terms_of_use = nothing)
    datadep = DataDeps.registry[depname]
    with_accept(i_accept_the_terms_of_use) do
        DataDeps.download(datadep, dir)
        nothing
    end
end
```

**Comment by oxinabox** [comment]
I think the name `i_accept_the_terms_of_use` is not quiet right.
In that the Y/N is not just terms of use, it is also "I accept that this will be downloaded",
and further some things (that are public domain for example) may have no terms of use.
