### ISSUE TITLE
Use ProgressMeter.jl?

### ISSUE THREAD

**Issue by juliohm** [oxinabox/DataDeps.jl#114]
Have you considered ProgressMeter.jl to show the download progress? It would be a nice feature.

**Comment by oxinabox** [comment]
This is a problem for HTTP.jl.
It is a question of HTTP.download and how that displays its progress.

**Comment by juliohm** [comment]
You prefer to improve the HTTP.download progress display than to use ProgressMeter.jl, is that correct?

**Comment by juliohm** [comment]
Really nice package btw! I've just downloaded a tar.gz, I wonder if there is any functionality to unpack the archive directly in the produced DataDep folder.

**Comment by oxinabox** [comment]
> You prefer to improve the HTTP.download progress display than to use ProgressMeter.jl, is that correct?

Something like that yes, because it faces all users of `HTTP.download`.
not just DataDeps.

**Comment by oxinabox** [comment]
> Really nice package btw! I've just downloaded a tar.gz, I wonder if there is any functionality to unpack the archive directly in the produced DataDep folder.

the `unpack` function.

can add `post_fetch_method = unpack` to the datadeps registration block
