### ISSUE TITLE
Dead blogpost link in beginning of docs

### ISSUE THREAD

**Issue by racinmat** [oxinabox/DataDeps.jl#118]
http://white.ucc.asn.au/2018/01/18/DataDeps.jl-Repeatabled-Data-Setup-for-Repeatable-Science.html mentioned in the beginning of https://www.oxinabox.net/DataDeps.jl/stable/ in `For a few examples of its usefulness see this blog post` is not working.

**Comment by oxinabox** [comment]
Same blog post exists at https://www.oxinabox.net

There will be a redirect added shortly.
Just waiting for DNS to get updated.

Could update the link itself though.

**Comment by oxinabox** [comment]
Working now
