### ISSUE TITLE
Input prompt triggered in non-interactive session

### ISSUE THREAD

**Issue by Evizero** [oxinabox/DataDeps.jl#12]
This is different than how I used to implement it. I can see an argument for allowing, say, a script to trigger the input prompt. That said, I think it complicates things in some automated environment. 

What do you think about throwing an error in case the "always accept" option is not set and the session is not interactive?

**Comment by oxinabox** [comment]
Indeed it is different.
I personally run most scripts via `julia myscript.jl` not via REPL + `include("myscript.jl")`
(Which conversely means the behavior of a few of your things cause problems for me)

The problem does indeed occur in CI that if you forget to set the environment variable it will just make CI hang til it times out.
But when that happens it is pretty obvious that CI is handing and has timed out from the logs,
and then setting the environment variable is easy.

**Comment by Evizero** [comment]
Ok, I can understand that preference. My main intention here was to see how strong you feel about this. I'll play with it some more and see if I either get used to it or find a way to work around it

**Comment by oxinabox** [comment]
I wonder what the best way to tell the program that reading from STDIN is not acceptable?
Maybe there should be a `Base` function, like `isinteractive()` but set-able.

**Comment by alyst** [comment]
Would it be possible to automatically detect CI (`get(ENV, "CI")`) and disable the prompt in that case? If it's CI session and `DATADEPS_ALWAYS_ACCEPT` is false/not set that should probably result in an error in `download()`?

**Comment by oxinabox** [comment]
I was considering this. Can you open a fresh issue for it? ( just copy paste is fine)
