### ISSUE TITLE
`mkpath(first(default_loadpath))` only executed at compile time

### ISSUE THREAD

**Issue by Evizero** [oxinabox/DataDeps.jl#13]
Maybe we should move this line : https://github.com/oxinabox/DataDeps.jl/blob/master/src/locations.jl#L19 to a module `__init__()` ? The current situation means that if a user at any time deletes `~/.julia/datadeps` then the module is more or less in a broken state, as it does not create the folder anymore until the next time it is precompiled. This results in:

```
LoadError: No possible save path
```

by the way, unsure if on purpose or not but I can only make the `RegisterDataDep(...)` work in MLDatasets, if I put that command into the module `__init__()`. Probably for the same reason, as otherwise the `DataDeps.registry` is empty during runtime

**Comment by oxinabox** [comment]
I'm really unfamilar with `__init__()`,
and how it differs from just doing things at the top level.
I've never had to use it.

Does it relate to precompilation? (I've also mostly not used that at all)


>by the way, unsure if on purpose or not but I can only make the RegisterDataDep(...) work in MLDatasets, if I put that command into the module __init__

Not on purpose.
My intend was that `RegisterDataDep` would be called at top-level.

**Comment by Evizero** [comment]
> Does it relate to precompilation? (I've also mostly not used that at all)

Right, well, I think so. AFAICT the top level code in your module is only executed during pre-compilation. A good example for making use of that you have seen before is here: https://github.com/malmaud/TensorFlow.jl/blob/master/src/TensorFlow.jl#L4

**Comment by oxinabox** [comment]
Ah, I should redo a bunch of the docs as well as change the package to make sure that works.

**Comment by oxinabox** [comment]
closed in #16
