### ISSUE TITLE
Prompt fails on Pluto

### ISSUE THREAD

**Issue by juliohm** [oxinabox/DataDeps.jl#138]
The download prompt asking the user wants to download the dataset fails on Pluto. Is there a workaround to avoid asking the question? Or a workaround that uses PlutoUI.jl elements to get the answer?

**Comment by oxinabox** [comment]
Set `ENV["DATADEPS_ALWAYS_ACCEPT"]="true"` to avoid asking the question

**Comment by juliohm** [comment]
That is true! Problem solved. Thanks.

**Comment by greimel** [comment]
Sorry for resurrecting this issue. But I wonder if there's a better solution.

I am using Pluto notebooks to for teaching and distributing my research. So it would be nice if I wouldn't have make students, co-authors and others to fiddle around with their environment variables.

**Comment by oxinabox** [comment]
It seems like this is a problem for Pluto.
Jupyter happily turns `readline(stdin)` into a input text box.
Pluto probably should do the same.
