### ISSUE TITLE
Closer integration with DrWatson

### ISSUE THREAD

**Issue by NicholasWMRitchie** [oxinabox/DataDeps.jl#146]
DataDeps is really useful when creating DrWatson reproducible data analysis projects.  However, it would be great if it were possible to register the `joinpath(datadir(),"exp_raw")` or similar as the directory into which the file is downloaded.

**Comment by oxinabox** [comment]
You can, by creating that directory and pushing it in the `DATADEPS_LOADPATH` enviroment variable.

Should look like:

```julia
ENV["DATADEPS_LOAD_PATH"] = mkpath(joinpath(datadir(),"exp_raw"))
```

See https://www.oxinabox.net/DataDeps.jl/stable/z10-for-end-users/#Configuration-1

When saving, DataDeps.jl basically starts from the start of it's load path, (which has a ton of default locations, but starts with the envvar) and saves to the first one it can (in terms of actually existing and being writable).
When loading it is similar (except it first checks for one local to the package directory) where it goes from the start and searches downwards til it hits one with the folder it wants -- and if it doesn't find it downloads.

**Comment by NicholasWMRitchie** [comment]
Thanks! Works like a charm.
