### ISSUE TITLE
Printing more than the datadep string on download

### ISSUE THREAD

**Issue by Evizero** [oxinabox/DataDeps.jl#15]
When a download is "triggered" DataDeps simply prints the dataset description and the prompt. I think it would be nice if at first there was some info message stating context to whats going on. Especially if the download was triggered by some backend code and not by some explicit user command. 

maybe something like

> This program requested access to the data dependency "MNIST".

**Comment by Evizero** [comment]
Also. Personally I think it would be better to not print the prompt as "info", but simply using a plain `print`, `println`

**Comment by oxinabox** [comment]
Hmm yes. I think so.
