### ISSUE TITLE
Documentation website is outdated, `gh-pages` is not being updated

### ISSUE THREAD

**Issue by fingolfin** [oxinabox/DataDeps.jl#162]
The latest commit to the `master` branch of repository was September 1, 2022. But the `gh-pages` branch was last updated Nov 21, 2020. As such it misses all releases after 0.7.4.

I noticed because there were typos in it I wanted to fix which turned out to be already fixed (but `codespell` found some more, hence PR #161).

**Comment by oxinabox** [comment]
This is #85 I really need to find  time to fix the docs build
