### ISSUE TITLE
Nondeterministic error in CI saying there is no writable folder in the load path

### ISSUE THREAD

**Issue by gdalle** [oxinabox/DataDeps.jl#169]
Hi there,
I recently encountered a weird error in the CI of a package calling DataDeps.jl:
```julia
┌ Error: No writable path exists to save the data. Make sure there exists as writable path in your DataDeps Load Path.
│ See https://www.oxinabox.net/DataDeps.jl/stable/z10-for-end-users/#The-Load-Path-1
│ The current load path contains:
│   cands =
│    8-element Vector{String}:
│     "/home/runner/.julia/datadeps"
│     "/opt/hostedtoolcache/julia/1.10.0/x64/local/share/julia/datadeps"
│     "/opt/hostedtoolcache/julia/1.10.0/x64/share/julia/datadeps"
│     "/home/runner/datadeps"
│     "/scratch/datadeps"
│     "/staging/datadeps"
│     "/usr/share/datadeps"
│     "/usr/local/share/datadeps"
└ @ DataDeps ~/.julia/packages/DataDeps/1KjBt/src/locations.jl:116
Benchmarks: Error During Test at /home/runner/work/MultiAgentPathFinding.jl/MultiAgentPathFinding.jl/test/runtests.jl:22
  Got exception outside of a @test
  LoadError: DataDeps.NoValidPathError("No writable path exists to save the data.")
```
Here's the [CI log](https://github.com/gdalle/MultiAgentPathFinding.jl/actions/runs/7504175656/job/20430588929). The weird thing about it is:

- this was the first time this ever happened to me (in this package or others)
- I resolved it by re-running CI (the last commit in [this PR](https://github.com/gdalle/MultiAgentPathFinding.jl/pull/12) fixed it by changing an unrelated typo)

Any idea what this could be?

**Comment by oxinabox** [comment]
That's weird.
It either means no directory on inm the listed load path exists,
or if they existed then they had read-only permissions.

I would guess, some kinda transient but with the CI runner, maybe it initialized wrong some how.

I wouldn't worry about it unless it reoccurs

**Comment by gdalle** [comment]
It just happened again ^^
https://github.com/gdalle/MultiAgentPathFinding.jl/actions/runs/7528620756/job/20491204694

**Comment by oxinabox** [comment]
I am hopeful that this will have been fixed by #167

**Comment by IanButterworth** [comment]
This is likely due to the cache action. Yeah that PR should fix it I guess

**Comment by oxinabox** [comment]
closing this, reopen if it reoccurs
