### ISSUE TITLE
Change to scratch breaking?

### ISSUE THREAD

**Issue by theogf** [oxinabox/DataDeps.jl#171]
Isn't the change to use `Scratch.jl` breaking?
Specifically this line:

https://github.com/oxinabox/DataDeps.jl/pull/167/files#diff-5b81a76e4a8ea96c096d34b1c4e05817631e527cf6300068c1c0ea3ceb7d9d8eL5

If I had my data in `.julia/datadeps`, specifically by adding it there manually, now `DataDeps.jl` is completely unable to find it.

For retrocompatibility, it would be good to keep `Base.DEPOT_PATH` in the `standard_paths` ?

**Comment by oxinabox** [comment]
Yes, good point we can keep it in there, just lower down so it is still read but not written to.
I will PR presently
