### ISSUE TITLE
At some point after version 0.7.0, DataDeps.jl broke WordTokenizers.jl

### ISSUE THREAD

**Issue by ablaom** [oxinabox/DataDeps.jl#173]
See here: https://github.com/JuliaText/WordTokenizers.jl/issues/64 (**edited**)

This is effecting a number of downstream packages, such as TextAnalysis.jl

**Comment by oxinabox** [comment]
You didn't link to an issue on WordTokenizers or a failing CI or anything.
So I don't have context to know what you mean

**Comment by ablaom** [comment]
Apologies. Link above fixed.

Thanks for the prompt attention.

**Comment by ablaom** [comment]
In a fresh Julia depot I am unable to reproduce. Closing for now.

Thanks @oxinabox again for the prompt attention.
