### ISSUE TITLE
Add doc string to RegisterDataDep

### ISSUE THREAD

**Issue by oxinabox** [oxinabox/DataDeps.jl#37]
Seems crazy, but apparently while all the internal methods have doc strings
`RegisterDataDep` does not.

Can basically copy paste from the readme

**Comment by oxinabox** [comment]
Registering a datadep doesn't touch the filesystem. Accessing it does. (Esp the first time)

**Comment by mbesancon** [comment]
ok my bad I thought the information was saved, I just tested registering, restarting julia and calling, doesn't work, as expected.

**Comment by oxinabox** [comment]
Ah, no. What you want to do is create a file containing the registration block, and then `include` that file.

**Comment by oxinabox** [comment]
closed in #41
