### ISSUE TITLE
Download data  that require to fill form and get link by email?

### ISSUE THREAD

**Issue by chengchingwen** [oxinabox/DataDeps.jl#83]
There are some datasets require you to fill in some form or fill you email on the website and later they will send a email to you with the download link inside. For example: [ROCStories Story Cloze Test](http://cs.rochester.edu/nlp/rocstories/). What is the best strategy for handling this kind of datasets with DataDeps.jl?

**Comment by oxinabox** [comment]
Assuming the link expires or something, it is difficult.

A `ManualDataDep` will always work.
This is one of the cases it was built for.
But `ManualDataDep`s are well manual.

A more advanced trick would be to write a custom `fetch_method` that requests the URL from the user. And set the remote path to a dummy string in the registration block.
Somthing like 
```
fetch_method= function(dummyremote, localdir)
    println("what is URL from email?")
    r_url = readline()
    DataDeps.fetch_http(remotepath, localdir)
end
```

I think the above should work.


If the link is constant but secret (security though obscurity)
And you don't want to put it in your source code you can put it into an environment variable and then use `ENV["Varname]"` to put that in your registration block.

**Comment by chengchingwen** [comment]
Thanks. 
The custom `fetch_method` works fine. So it seems that the best strategy is to let the user copy-paste the link they get and then download it.
