### ISSUE TITLE
Download prompt repeats forever in package build

### ISSUE THREAD

**Issue by rdeits** [oxinabox/DataDeps.jl#84]
I was trying to follow http://white.ucc.asn.au/DataDeps.jl/stable/z20-for-pkg-devs.html#Installing-Data-Eagerly-1 and download a data dependency at `pkg> build` time, but I'm having trouble getting it to work. 

As an example, I've created the following `deps/build.jl` file: 

```
using DataDeps

register(DataDep("foo",
                 "",
                 "https://foo.bar"))

datadep"foo"
```

Running `pkg> build MyPackage` hangs forever. The `deps/build.log` file shows: 

```
This program has requested access to the data dependency foo.
which is not currently installed. It can be installed automatically, and you will not see this message again.




Do you want to download the dataset from https://foo.bar to "/home/rdeits/.julia/datadeps/foo"?
[y/n]
Do you want to download the dataset from https://foo.bar to "/home/rdeits/.julia/datadeps/foo"?
[y/n]
Do you want to download the dataset from https://foo.bar to "/home/rdeits/.julia/datadeps/foo"?
[y/n]
```

with that prompt repeating forever. 

I've seen the same behavior when trying to load a datadep during package precompilation. 

Is this a bug, or should I be doing something differently? 

I've reproduced the issue with DataDeps 0.6.2 and `master`. 

```
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

**Comment by oxinabox** [comment]
I don't know why this is happennung in 0.6
I would have assumed it
This happens because of changes in how PKG does build.
It redirects the IO.
So one can no longer ask for user input.

**Comment by oxinabox** [comment]
Closed in https://github.com/oxinabox/DataDeps.jl/commit/7e3696e762bfb068b61288d54a526c703c2e0ae2
