### ISSUE TITLE
Docs on github pages are out of date

### ISSUE THREAD

**Issue by oxinabox** [oxinabox/DataDeps.jl#85]
For some reason the docs on github pages no longer match those in the docs folder on github.

Something is going wrong withe Documenter I guess, during the deploy stage on travis

**Comment by nickrobinson251** [comment]
Bump. :)
In particular "preupload_check" is not in the hosted documentation for this reason.

**Comment by oxinabox** [comment]
For some reason it is skipping deployment
https://travis-ci.org/oxinabox/DataDeps.jl/jobs/491586476#L504

**Comment by oxinabox** [comment]
Should just direct to https://pkg.julialang.org/docs/DataDeps/cCpxD/

**Comment by oxinabox** [comment]
Looks like it is something up with the keys
https://github.com/oxinabox/DataDeps.jl/actions/runs/3453045919/jobs/5763325278#step:7:84

**Comment by oxinabox** [comment]
Looks like I have fixed it, yay
