### ISSUE TITLE
`remove` command?

### ISSUE THREAD

**Issue by briochemc** [oxinabox/DataDeps.jl#93]
How do you remove a registered file within DataDeps.jl? 

I am pretty sure this is already doable since that's one of the steps when there is an issue and you chose the option to "erase and redownload" — but I am not sure how to use that or if there is even a function that is exported? I am using DataDeps.jl for a package that can load many different datasets but I would like to be able to run the CI tests locally on all these downloads without requiring a lot of memory and having to store everything.

**Comment by briochemc** [comment]
Perfect thanks!

**Comment by oxinabox** [comment]
Do you want to make a docs PR about it?

**Comment by briochemc** [comment]
I'm not sure I understand, I thought it was just me being dumb and the `rm` command was a default Julia one (and not part of DataDeps). Or did you mean for me to add that example removal to the docs?

**Comment by oxinabox** [comment]
> add that example removal to the docs?|

yes, this
