### ISSUE TITLE
Multiple URLS for same data

### ISSUE THREAD

**Issue by briochemc** [oxinabox/DataDeps.jl#94]
Sometimes, data is stored at many different URLs for redundancy. [Here](https://data.nodc.noaa.gov/thredds/catalog/ncei/woa/temperature/decav/5deg/catalog.html?dataset=ncei/woa/temperature/decav/5deg/woa18_decav_t00_5d.nc) is an example. It's a catalog of 8 URLs that contain the same NetCDF file with oceanographic temperature data from the World Ocean Atlas. Is it possible to register data with multiple URLs instead of only one?

Having DataDeps aware of this type of redundancy (and try the URLs until one works) would be great for robustness!
(CI fails for one of my packages because downloading from one URL sometimes randomly fails.)

**Comment by oxinabox** [comment]
It is not possible right now.
This is the issue  #7 lets continue any discussion in it there 
:-)
