### ISSUE TITLE
suggestion: citation function returning .bib

### ISSUE THREAD

**Issue by briochemc** [oxinabox/DataDeps.jl#98]
I am almost sure you thought about this, but I could not find it so I thought I'd create an issue.

Would it be possible to have a `citation` function that would return a string of the bibtex entry?
Something like:
```julia
julia> print(citation("FastText en")) # "FastText en" having been registered before...

@article{FastText_en,
 author    = "Bojanowski, P. and Grave, E. and Joulin, A. and Moulin, T.",
 title     = "Enriching Word Vectors with Subword Information",
 publisher = "Facebook",
 year      = 2042,
 address   = "USA",
}
```
that I can directly copy into by bibtex. 

Above I assume one would have registered `"FastText en"` with the data and an additional (optional?) field for the citation. Maybe it looked like:
```julia
julia> register(DataDep("FastText en",
    """
    Dataset: FastText Word Embeddings for English.
    Author: Bojanowski et. al. (Facebook)
    License: CC-SA 3.0
    Website: https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md
    
    300 dimentional FastText word embeddings, trained on Wikipedia

    Notice: this file is over 6.2GB
    """,
    "https://s3-us-west-1.amazonaws.com/fasttext-vectors/wiki.en.vec",
    "ba5420ac217fb34f15f58ded0d911a4370dfb1f3341fa7511a49ae74c87de282",
    citation = """
    @article{FastText_en,
     author    = "Bojanowski, P. and Grave, E. and Joulin, A. and Moulin, T.",
     title     = "Enriching Word Vectors with Subword Information",
     publisher = "Facebook",
     year      =  2042,
     address   = "USA",
    }
    """
))
```

I think this makes sense for DataDeps to align itself with Julia packages (i.e., code) that now generally contain a `CITATION.bib` file.

**Comment by oxinabox** [comment]
Julia isn't right now exposing a way to read that `CITATION.bib`  file in code.
I would say that aligning oneself with that would be to just include
that data's citation inside the `CITATION.bib` file.
Probably with the same key as the DataDepName or something like that.
This is the plan (as i understand it) for how packages would include references to the original works that are cited for various functions.
(as well as including the citation details for the package itself at the top of in the CITATION.bib)

When and if Julia includes programatic access to the the CITATION.bib  we shound indeed support reading it.

**Comment by briochemc** [comment]
OK I see thanks!
